/* PROYECTO: Formando Campeones
   CICLO 4 - SEGURIDAD
   OBJETIVO: Definición de roles y permisos con paquetes actores (WRAPPER)
   NOTA: Ejecutar conectado como SYSTEM o DBA con privilegios suficientes
*/

/* PASO 1: CREAR ROLES COMUNES (C## requerido en Oracle Multitenant CDB) */
CREATE ROLE C##ADMINISTRADOR;
CREATE ROLE C##ENTRENADOR;
CREATE ROLE C##GERENTE;

/* PASO 2: DAR PERMISOS A LOS ROLES */
GRANT EXECUTE ON USUARIO_CAMILO.PA_ADMINISTRADOR TO C##ADMINISTRADOR;
GRANT EXECUTE ON USUARIO_CAMILO.PA_ENTRENADOR TO C##ENTRENADOR;
GRANT EXECUTE ON USUARIO_CAMILO.PA_GERENTE TO C##GERENTE;


/* PASO 3: PROBAR ROLES CON EL USUARIO */

/* ADMINISTRADOR */
GRANT C##ADMINISTRADOR TO USUARIO_CAMILO;

/* pruebas */

/* quitar rol */
REVOKE C##ADMINISTRADOR FROM USUARIO_CAMILO;

/* ENTRENADOR */
GRANT C##ENTRENADOR TO USUARIO_CAMILO;

/* pruebas */
/* quitar rol */
REVOKE C##ENTRENADOR FROM USUARIO_CAMILO;


/* GERENTE */
GRANT C##GERENTE TO USUARIO_CAMILO;

/* pruebas */
/* quitar rol */
REVOKE C##GERENTE FROM USUARIO_CAMILO;


/* ROL FINAL ACTIVO */
GRANT C##ADMINISTRADOR TO USUARIO_CAMILO;

COMMIT;


