/* PROYECTO: Formando Campeones
   CICLO 4 - ELIMINACIÓN PAQUETES ACTORES
   
   OBJETIVO: Limpiar paquetes de seguridad (actores) antes de recrearlos
*/

/* ELIMINAR PAQUETES ACTORES */
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY PA_ADMINISTRADOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE PA_ADMINISTRADOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY PA_ENTRENADOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE PA_ENTRENADOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BODY PA_GERENTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE PA_GERENTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
