/* PROYECTO: Formando Campeones
   CICLO 4 - ELIMINACIÓN SEGURIDAD
   OBJETIVO: Revocar roles y permisos */

/* REVOCAR PERMISOS EN PAQUETES ACTORES */
REVOKE EXECUTE ON PA_ADMINISTRADOR FROM C##ADMINISTRADOR;
REVOKE EXECUTE ON PA_ENTRENADOR FROM C##ENTRENADOR;
REVOKE EXECUTE ON PA_GERENTE FROM C##GERENTE;

/* REVOCAR ASIGNACIÓN DE ROLES A USUARIOS */
REVOKE C##ADMINISTRADOR FROM USUARIO_CAMILO;

/* ELIMINAR ROLES */
DROP ROLE C##ADMINISTRADOR;
DROP ROLE C##ENTRENADOR;
DROP ROLE C##GERENTE;

COMMIT;
